### ISSUE TITLE
[ Discussion ] Add PEP8 config file to Github

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/SickRage#446]
Since PEP8 can use a .pep8 file in the current directory for it's config it'd a good idea to add one to this repo so people that're using linters in their IDE can have it setup automatically with the rules we are/aren't following in PEP8.

I'd also like to ask that we set the allowed line length to a larger size than 79 as it ends up making a lot of the code wrap at times that it shouldn't. If we all agree to a certain length we can then set it along with all other global settings inside of this new file.

@pymedusa/contributors @pymedusa/developers @pymedusa/owners @pymedusa/administrators @pymedusa/moderators

**Comment by labrys** [comment]
100 is what we shoot for as a target but 120 is fine.  Anything over 120 should be avoided if possible, but in some instances, (e.g, urls, regexs) that may not be.  Me personally i'm against pep8 files because people tend to add rules to them more to be lazy than to suppress invalid warnings, which is what they should be used for, but if everyone wants them, we can add them.

**Comment by OmgImAlexis** [comment]
The main reason I opened this was the line issue and the fact that most PEP8 plugins will use a global PEP8 config file in `~/` if there isn't one in the current dir meaning they may have overrides that then have to be fixed later on. Even with just the file being in there it'd cause the linter to use our one instead of their own.
