### ISSUE TITLE
PROPER thread doesn't have a scheduler

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#534]
so it runs together with dailysearch and backlogsearch causing 'too many requests' in RARBG (it may cause issues in other providers that we don't know of - only confirmed is RARBG).  Proper thread should be queued like the other threads.

**Comment by p0psicles** [comment]
What is it guys? Before you where convinced the proper thread, should be run in parallel to the others?

**Comment by medariox** [comment]
I wouldn't know what the advantage of running proper on parallel would be and why it has been done like that in the first place, anyone can shed some light on this?

**Comment by duramato** [comment]
Propers are something that needs to run along side everything, my daily takes ages and so does backlog searches, and mine arent the worst.
Propers run every ~3h .
Rarbg is the only one with this issue and it isnt by only 1 provider that you shouldnt be running a  propers search, if i get a daily snatch , a proper isnt pred not long after , if i have a backlog search running, again if someone has lower quality ep its even worst, i will get the proper hours after if it gets queued up after a backlog.
Rarbg by itself has issues even with a backlog search or a simple multi scene exception epidsode search and blocks after x reqs.
In my eyes its an issue with rarbg. Since no other provider of my 50 has that issue.

**Comment by rarbg** [comment]
Well :) if you are willing to keep our internal id (lets call it rarbg_id ) in your database for a release, i would be happy to provide you with an API that will return if there are PROPERed torrents for that id.

**Comment by labrys** [comment]
@rarbg I would definitely be interested in that, ofc no rush, as we have a lot of stuff in the works.

**Comment by rarbg** [comment]
@fernandog @labrys 
well , one other idea i have is to make you API that returns the last 1000 proper releases names(which is ~3 months back) , from there you can understand what you need to search for thus reducing the requests to the original api to bare minimum ?

**Comment by p0psicles** [comment]
Okay this issue thread has not been updated in a while. Also No real arguments have been provided to change the properSearcher. Going to close this
