### ISSUE TITLE
Auto post-processed download remains "snatched"

### ISSUE THREAD

**Issue by medariox** [pymedusa/SickRage#549]
Branch/Commit: develop/d491854671d0e8154adec389c61f27de2d7c337d
OS: Ubuntu 15
What you did: Snatch an episode from manual search
What happened: Download is auto post-processed, but status remains "snatched"
What you expected: The status to change to "downloaded"

Screenshot:
![image](https://cloud.githubusercontent.com/assets/2893509/15087779/7e4c5548-13ec-11e6-9bcc-43d4c63d9ae3.png)

History shows correct status:
![image](https://cloud.githubusercontent.com/assets/2893509/15088098/d483501c-13ef-11e6-88c5-36d5656282bb.png)

Additional info:
* Restarting Medusa changes the status to the correct one.

**Comment by p0psicles** [comment]
Can you try to get one response of http://home.headshots.nl/sickrage/home/getManualSearchStatus?show=[indexerid], when it's not correctly showing?

**Comment by medariox** [comment]
This time I snatched an episode and the status didn't changed to "snatched", it remained as ignored.
Here is the response as you requested:
```{"episodes": [{"status": "Ignored", "episode": 4, "show": 74897, "episodeindexid": "5489984", "season": 15, "quality": "N/A", "searchstatus": "finished", "overview": "skipped"}]}```
Thanks!

**Comment by p0psicles** [comment]
Well issue is that normally when downloading an episode through forced search it's added to a temporary list of downloaded/completed episodes. https://github.com/pymedusa/SickRage/blob/develop/sickbeard/search_queue.py#L40.

In some cases the list is still not properly updated, when an episode is manual searched and snatched.

**Comment by p0psicles** [comment]
Ok, the problem is this...
Currently i'm reading the searchThreads and a list name FORCED_SEARCH_HISTORY. That works fine if the status can only update from the queues.

The issue starts, when it's also possible to update the status from different angles. Like for example when a download is finished and is post processed. That has nothing todo with the episode status located in the threads.

I've currently solved it, by updating the status to db from manual search. Forced search already did that. Now i'm querying the db, to check the actual status. But the downside is that /getManualSearchStatus is hitting the db every 5s.

Maybe an alternative could be to trigger update the in memory showList (if it has episode info at all), and use that. But I don't know if that's possible without rewriting allot.

**Comment by fernandog** [comment]
@p0psicles sorry If is a dumb question. but when after we call snatchEpisode function, is follows the same process as forced search or backlog search. So why manual search has to do something different from them? It needs to do the same.

DB is updated in "snatchEpisode" here:
https://github.com/pymedusa/SickRage/blob/develop/sickbeard/search.py#L161
https://github.com/pymedusa/SickRage/blob/develop/sickbeard/history.py#L75

as @medariox said, DB is OK - you can see that in the "history" SS

History shows correct status:
![image](https://cloud.githubusercontent.com/assets/2893509/15088098/d483501c-13ef-11e6-88c5-36d5656282bb.png)

so IMHO its only JS issue. If FORCEDSEARCH is ok, we should do the same. because after some point (after snatchEpisode function) , the process is the same for both

**Comment by p0psicles** [comment]
@fernandog apparently it does not follow the same process. As with the forcedSearch, after snatching, an episode is PP, and it's automatically picked up without reloading the page.

While through manual search that does not work. I can search, why it's working properly in forcedSearch though.

**Comment by fernandog** [comment]
@p0psicles sorry, didn't understood this "and it's automatically picked up without reloading the page."

dumb question: why JS is overriding the result from webserve (correct result?)

**Comment by p0psicles** [comment]
Because it does that through periodic polling. It gets a json with a list of episodes and their latest status. That way you don't need to reload the page, to see status changes.

**Comment by fernandog** [comment]
that was added after manual search of always worked like that?

**Comment by p0psicles** [comment]
No that was added with FKA manual search (now called forced search)

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/SickRage/pull/568
