### ISSUE TITLE
Map guessit screen_size and format to Qualities

### ISSUE THREAD

**Issue by medariox** [pymedusa/SickRage#767]
`Show.Name.S02e11[Mux.-.720p.-.H264.-.Ita.Eng.Ac3.-.Sub.Ita.Eng].GiuseppeTnT.LittleLinx`
Quality is unknown.

`Show.Name.S02e11.[Mux.-.1080p.-.H264.-.Ita.Eng.Ac3.-.Sub.Ita.Eng].WEBMux`
Quality is 1080p (correct).

**Comment by ratoaq2** [comment]
One thing that you should be aware:
We're still using the quality that comes from Quality module. Guessit probably parses this quality correctly, but we're not mapping the guessit qualities to Quality.

When I started this discussion on IRC, it was decided to do it in a later stage since Quality should be revisited.

**Comment by medariox** [comment]
Thanks for the info, I didn't remember that.

Anyway, I think the issue here is that the name doesn't contain the video source info, but just the resolution and the fact that it is a 'Mux'. So it's impossible to determine the source HDTV, WEBDL, SDTV, etc. I think we can close this as it's not an actual issue.
